name: Strajk Bowling

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install modules
  #       run: npm install
  #     - name: Build dist
  #       run: npm run build

  test:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Test
        run: npm run coverage
      - name: build
        run: npm run build