name: Strajk Bowling

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install modules
  #       run: npm install
  #     - name: Build dist
  #       run: npm run build

  test:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: run tests with coverage
        run: npm run coverage
      # - name: build
      #   run: npm run build
      - name: Check the coverage
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: coverage/clover.xml
          required-percentage: 90