name: Strajk Bowling

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        run: npm install
      - name: Tests
        run: npm run test
  build:
    need: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build